server:
  port: 6060

spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决重写PermitAllUrlProperties里getPatternsCondition()为空的问题

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.181:3306/pig_codegen?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

  freemarker:
    cache: false
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/

  redisson.address: redis://192.168.3.181:6379
  redis:
    host: 192.168.3.181
#  redisson.address: redis://localhost:6379
knife4j:
  # 开启增强配置
  enable: true
xxl:
  job:
    accessToken: demo
    admin.addresses: http://192.168.3.181:5004/xxl-job-admin
    executor:
      appname: lind
      port: 9971
      ip:
# 加解密根密码
jasypt:
  encryptor:
    password: pig #根密码

auth:
  name: lind-local
  date: 2017-9-26

mybatis-plus:
  typeAliasesPackage: com.lind.fast.demo.entity
  typeHandlersPackage: com.lind.common.mybatis.handler
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lind.fast.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Logger Config
logging:
  level:
    mybatis.mate: INFO
oss:
  endpoint: http://minio.pig4cloud.com
  access-key: lengleng
  secret-key: lengleng

anti.reptile:
  enabled: true
  ip-rule:
    enabled: true
