server:
  port: 6060

spring:
  application:
    name: @artifactId@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.181:3306/pig_codegen?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
xxl:
  job:
    accessToken: demo
    admin.addresses: http://192.168.3.181:5004/xxl-job-admin
    executor:
      appname: lind
      port: 9971
      ip:
# 加解密根密码
jasypt:
  encryptor:
    password: pig #根密码



mybatis-plus:
  typeAliasesPackage: com.lind.fast.demo.entity
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lind.fast.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true
