server:
  port: 6060

spring:
  application:
    name: @artifactId@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pig_codegen?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

xxl:
  job:
    accessToken: demo
    admin.addresses: http://localhost:5004/xxl-job-admin
    executor:
      appname: lind
      port: 9971
      ip:
# 加解密根密码
jasypt:
  encryptor:
    password: pig #根密码



mybatis-plus:
  typeAliasesPackage: com.lind.fast.demo.entity
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.lind.fast.demo.entity
  configuration:
    mapUnderscoreToCamelCase: true
