server:
  port: 3000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#  config:
#    import:
#      - nacos:application-@profiles.active@.yml
#      - nacos:${spring.application.name}-@profiles.active@.yml
  cache:
    type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: pig-redis
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
security:
  oauth2:
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs
        - /actuator/**
